#.travis.yml
sudo: required
dist: trusty
language: node_js
node_js:
  - "6.9"


branches:
  only:
    - develop
    - master

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g @angular/cli

script:
  - cp src/environments/parameters.ts.dist  src/environments/parameters.ts
  - ng build --env=prod --aot
  - ng test --watch=false

notifications:
  email:
    on_failure: change
    on_success: change