export const ErrorMessage = {
    form_not_submitted: 'E-Mail and/or password syntax is incorrect',
    form_not_valid: 'E-Mail and/or password syntax is incorrect',
    suggest_brain_key_error: 'System error. Please try again later',
    create_account_with_brain_key_error: 'System error. Please try again later',
    user_already_exist: 'User already exist',
    system_error: 'System error. Please try again later',
    confirm_registration: 'Confirm registration',
    time_expired: 'Time expired',
    incorrect_string_hash: 'Your E-Mail and/or password is incorrect',
    hint_incorrect_string_hash: 'Wrong password',
    verify_signature_error: 'Your E-Mail and/or password is incorrect',
    hint_verify_signature_error: 'Wrong password',
    incorrect_signature: 'Your E-Mail and/or password is incorrect',
    hint_incorrect_signature: 'Wrong password',
    already_confirmed: 'Already confirmed',
    user_not_found: 'User not found',
    email_error: 'E-Mail error',
    go_to_ico_reclaim: `Please, visit <a href="https://icoreclaim.decentgo.com" target="_blank">https://icoreclaim.decentgo.com</a> first to reclaim your DCT balance`,
    incorrect_credentials: `Please <a href="/sign-in">Log in</a> directly using your ICO reclaim account credentials`,
    blacklisted_email: 'Sign up with reputable E-Mail'
};
